# Generated by Django 5.0.3 on 2024-03-09 06:39

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=home.models.userImagePath, verbose_name='Blog Picture'),
        ),
    ]
